from flask_login import UserMixin
from . import db


class User(UserMixin, db.Model):
    user_id        = db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    user_firstname = db.Column(db.String(50), nullable=True)
    user_lastname  = db.Column(db.String(50), nullable=True)
    user_email     = db.Column(db.String(50), nullable=False, unique=True)
    user_mob       = db.Column(db.Integer, nullable=True, unique=True)
    user_sex       = db.Column(db.String(15), nullable=True)
    user_password  = db.Column(db.String(80), nullable=False)

    # UserMixin provides a get_id method, here one of our attributes is user_id. To resolve this conflict, this method is defined.
    def get_id(self):
        return (self.user_id)

class UserCategory(db.Model):
    user_id                         =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    art_and_entertainment           =   db.Column(db.Boolean, default=False, nullable=False)
    college_and_university          =   db.Column(db.Boolean, default=False, nullable=False)
    event                           =   db.Column(db.Boolean, default=False, nullable=False)
    food                            =   db.Column(db.Boolean, default=False, nullable=False)
    nightlife_spot                  =   db.Column(db.Boolean, default=False, nullable=False)
    outdoors_and_recreation         =   db.Column(db.Boolean, default=False, nullable=False)
    professional_and_other_places   =   db.Column(db.Boolean, default=False, nullable=False)
    residence                       =   db.Column(db.Boolean, default=False, nullable=False)
    shop_and_service                =   db.Column(db.Boolean, default=False, nullable=False)
    travel_and_transport            =   db.Column(db.Boolean, default=False, nullable=False)

class ArtAndEntertainment(db.Model):
    user_id                         =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    amphitheater                    =   db.Column(db.Boolean, default=False, nullable=False)
    aquarium                        =   db.Column(db.Boolean, default=False, nullable=False)
    arcade                          =   db.Column(db.Boolean, default=False, nullable=False)
    art_gallery                     =   db.Column(db.Boolean, default=False, nullable=False)
    bowling_alley                   =   db.Column(db.Boolean, default=False, nullable=False)
    casino                          =   db.Column(db.Boolean, default=False, nullable=False)
    circus                          =   db.Column(db.Boolean, default=False, nullable=False)
    comedy_club                     =   db.Column(db.Boolean, default=False, nullable=False)
    concert_hall                    =   db.Column(db.Boolean, default=False, nullable=False)
    country_dance_club              =   db.Column(db.Boolean, default=False, nullable=False)
    disc_golf                       =   db.Column(db.Boolean, default=False, nullable=False)
    escape_room                     =   db.Column(db.Boolean, default=False, nullable=False)
    exhibit                         =   db.Column(db.Boolean, default=False, nullable=False)
    general_entertainment           =   db.Column(db.Boolean, default=False, nullable=False)
    go_kart_track                   =   db.Column(db.Boolean, default=False, nullable=False)
    historic_site                   =   db.Column(db.Boolean, default=False, nullable=False)
    karaoke_box                     =   db.Column(db.Boolean, default=False, nullable=False)
    laser_tag                       =   db.Column(db.Boolean, default=False, nullable=False)
    memorial_site                   =   db.Column(db.Boolean, default=False, nullable=False)
    mini_golf                       =   db.Column(db.Boolean, default=False, nullable=False)
    movie_theater                   =   db.Column(db.Boolean, default=False, nullable=False)
    museum                          =   db.Column(db.Boolean, default=False, nullable=False)
    music_venue                     =   db.Column(db.Boolean, default=False, nullable=False)
    pachinko_parlor                 =   db.Column(db.Boolean, default=False, nullable=False)
    performing_arts_venue           =   db.Column(db.Boolean, default=False, nullable=False)
    pool_hall                       =   db.Column(db.Boolean, default=False, nullable=False)
    public_art                      =   db.Column(db.Boolean, default=False, nullable=False)
    racecourse                      =   db.Column(db.Boolean, default=False, nullable=False)
    racetrack                       =   db.Column(db.Boolean, default=False, nullable=False)
    roller_rink                     =   db.Column(db.Boolean, default=False, nullable=False)
    salsa_club                      =   db.Column(db.Boolean, default=False, nullable=False)
    samba_school                    =   db.Column(db.Boolean, default=False, nullable=False)
    stadium                         =   db.Column(db.Boolean, default=False, nullable=False)
    theme_park                      =   db.Column(db.Boolean, default=False, nullable=False)
    tour_provider                   =   db.Column(db.Boolean, default=False, nullable=False)
    vr_cafe                         =   db.Column(db.Boolean, default=False, nullable=False)
    water_park                      =   db.Column(db.Boolean, default=False, nullable=False)
    zoo                             =   db.Column(db.Boolean, default=False, nullable=False)

class CollegeAndUniversity(db.Model):
    user_id                          =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    college_academic_building        =   db.Column(db.Boolean, default=False, nullable=False)
    college_administrative_building  =   db.Column(db.Boolean, default=False, nullable=False)
    college_auditorium               =   db.Column(db.Boolean, default=False, nullable=False)
    college_bookstore                =   db.Column(db.Boolean, default=False, nullable=False)
    college_cafeteria                =   db.Column(db.Boolean, default=False, nullable=False)
    college_classroom                =   db.Column(db.Boolean, default=False, nullable=False)
    college_gym                      =   db.Column(db.Boolean, default=False, nullable=False)
    college_lab                      =   db.Column(db.Boolean, default=False, nullable=False)
    college_library                  =   db.Column(db.Boolean, default=False, nullable=False)
    college_quad                     =   db.Column(db.Boolean, default=False, nullable=False)
    college_rec_center               =   db.Column(db.Boolean, default=False, nullable=False)
    college_residence_hall           =   db.Column(db.Boolean, default=False, nullable=False)
    college_stadium                  =   db.Column(db.Boolean, default=False, nullable=False)
    college_theater                  =   db.Column(db.Boolean, default=False, nullable=False)
    community_college                =   db.Column(db.Boolean, default=False, nullable=False)
    fraternity_house                 =   db.Column(db.Boolean, default=False, nullable=False)
    general_college_and_university   =   db.Column(db.Boolean, default=False, nullable=False)
    law_school                       =   db.Column(db.Boolean, default=False, nullable=False)
    medical_school                   =   db.Column(db.Boolean, default=False, nullable=False)
    sorority_house                   =   db.Column(db.Boolean, default=False, nullable=False)
    student_center                   =   db.Column(db.Boolean, default=False, nullable=False)
    trade_school                     =   db.Column(db.Boolean, default=False, nullable=False)
    university                       =   db.Column(db.Boolean, default=False, nullable=False)

class Event(db.Model):
    user_id             =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    christmas_market    =   db.Column(db.Boolean, default=False, nullable=False)
    conference          =   db.Column(db.Boolean, default=False, nullable=False)
    convention          =   db.Column(db.Boolean, default=False, nullable=False)
    festival            =   db.Column(db.Boolean, default=False, nullable=False)
    line_or_queue       =   db.Column(db.Boolean, default=False, nullable=False)
    music_festival      =   db.Column(db.Boolean, default=False, nullable=False)
    other_event         =   db.Column(db.Boolean, default=False, nullable=False)
    parade              =   db.Column(db.Boolean, default=False, nullable=False)
    sporting_event      =   db.Column(db.Boolean, default=False, nullable=False)
    stoop_sale          =   db.Column(db.Boolean, default=False, nullable=False)
    street_fair         =   db.Column(db.Boolean, default=False, nullable=False)
    trade_fair          =   db.Column(db.Boolean, default=False, nullable=False)

class Food(db.Model):
    user_id                                    =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    afghan_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    african_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    american_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    armenian_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    asian_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    australian_restaurant                      =   db.Column(db.Boolean, default=False, nullable=False)
    austrian_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    bbq_joint                                  =   db.Column(db.Boolean, default=False, nullable=False)
    bagel_shop                                 =   db.Column(db.Boolean, default=False, nullable=False)
    bakery                                     =   db.Column(db.Boolean, default=False, nullable=False)
    bangladeshi_restaurant                     =   db.Column(db.Boolean, default=False, nullable=False)
    belgian_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    bistro                                     =   db.Column(db.Boolean, default=False, nullable=False)
    breakfast_spot                             =   db.Column(db.Boolean, default=False, nullable=False)
    bubble_tea_shop                            =   db.Column(db.Boolean, default=False, nullable=False)
    buffet                                     =   db.Column(db.Boolean, default=False, nullable=False)
    burger_joint                               =   db.Column(db.Boolean, default=False, nullable=False)
    cafeteria                                  =   db.Column(db.Boolean, default=False, nullable=False)
    café                                       =   db.Column(db.Boolean, default=False, nullable=False)
    cajun_or_creole_restaurant                 =   db.Column(db.Boolean, default=False, nullable=False)
    caribbean_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    caucasian_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    coffee_shop                                =   db.Column(db.Boolean, default=False, nullable=False)
    comfort_food_restaurant                    =   db.Column(db.Boolean, default=False, nullable=False)
    creperie                                   =   db.Column(db.Boolean, default=False, nullable=False)
    czech_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    deli_or_bodega                             =   db.Column(db.Boolean, default=False, nullable=False)
    dessert_shop                               =   db.Column(db.Boolean, default=False, nullable=False)
    diner                                      =   db.Column(db.Boolean, default=False, nullable=False)
    donut_shop                                 =   db.Column(db.Boolean, default=False, nullable=False)
    dumpling_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    dutch_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    eastern_european_restaurant                =   db.Column(db.Boolean, default=False, nullable=False)
    english_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    falafel_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    fast_food_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    fish_and_chips_shop                        =   db.Column(db.Boolean, default=False, nullable=False)
    fondue_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    food_court                                 =   db.Column(db.Boolean, default=False, nullable=False)
    food_stand                                 =   db.Column(db.Boolean, default=False, nullable=False)
    food_truck                                 =   db.Column(db.Boolean, default=False, nullable=False)
    french_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    fried_chicken_joint                        =   db.Column(db.Boolean, default=False, nullable=False)
    friterie                                   =   db.Column(db.Boolean, default=False, nullable=False)
    gastropub                                  =   db.Column(db.Boolean, default=False, nullable=False)
    german_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    gluten_free_restaurant                     =   db.Column(db.Boolean, default=False, nullable=False)
    greek_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    halal_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    hawaiian_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    hot_dog_joint                              =   db.Column(db.Boolean, default=False, nullable=False)
    hungarian_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    indian_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    irish_pub                                  =   db.Column(db.Boolean, default=False, nullable=False)
    italian_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    jewish_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    juice_bar                                  =   db.Column(db.Boolean, default=False, nullable=False)
    kebab_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    latin_american_restaurant                  =   db.Column(db.Boolean, default=False, nullable=False)
    mac_and_cheese_joint                       =   db.Column(db.Boolean, default=False, nullable=False)
    mediterranean_restaurant                   =   db.Column(db.Boolean, default=False, nullable=False)
    mexican_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    middle_eastern_restaurant                  =   db.Column(db.Boolean, default=False, nullable=False)
    modern_european_restaurant                 =   db.Column(db.Boolean, default=False, nullable=False)
    molecular_gastronomy_restaurant            =   db.Column(db.Boolean, default=False, nullable=False)
    pakistani_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    pet_café                                   =   db.Column(db.Boolean, default=False, nullable=False)
    pizza_place                                =   db.Column(db.Boolean, default=False, nullable=False)
    polish_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    portuguese_restaurant                      =   db.Column(db.Boolean, default=False, nullable=False)
    poutine_place                              =   db.Column(db.Boolean, default=False, nullable=False)
    restaurant                                 =   db.Column(db.Boolean, default=False, nullable=False)
    russian_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    salad_place                                =   db.Column(db.Boolean, default=False, nullable=False)
    sandwich_place                             =   db.Column(db.Boolean, default=False, nullable=False)
    scandinavian_restaurant                    =   db.Column(db.Boolean, default=False, nullable=False)
    scottish_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    seafood_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    slovak_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    snack_place                                =   db.Column(db.Boolean, default=False, nullable=False)
    soup_place                                 =   db.Column(db.Boolean, default=False, nullable=False)
    southern_or_soul_food_restaurant           =   db.Column(db.Boolean, default=False, nullable=False)
    spanish_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    sri_lankan_restaurant                      =   db.Column(db.Boolean, default=False, nullable=False)
    steakhouse                                 =   db.Column(db.Boolean, default=False, nullable=False)
    swiss_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    tea_room                                   =   db.Column(db.Boolean, default=False, nullable=False)
    theme_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    turkish_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    ukrainian_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    vegetarian_or_vegan_restaurant             =   db.Column(db.Boolean, default=False, nullable=False)
    wings_joint                                =   db.Column(db.Boolean, default=False, nullable=False)

class   NightlifeSpot(db.Model):
    user_id                     =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    bar                         =   db.Column(db.Boolean, default=False, nullable=False)
    brewery                     =   db.Column(db.Boolean, default=False, nullable=False)
    lounge                      =   db.Column(db.Boolean, default=False, nullable=False)
    night_market                =   db.Column(db.Boolean, default=False, nullable=False)
    nightclub                   =   db.Column(db.Boolean, default=False, nullable=False)
    other_nightlife             =   db.Column(db.Boolean, default=False, nullable=False)
    strip_club                  =   db.Column(db.Boolean, default=False, nullable=False)


class OutdoorsAndRecreation(db.Model):
    user_id                     =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    athletics_and_sports        =   db.Column(db.Boolean, default=False, nullable=False)
    bathing_area                =   db.Column(db.Boolean, default=False, nullable=False)
    bay                         =   db.Column(db.Boolean, default=False, nullable=False)
    beach                       =   db.Column(db.Boolean, default=False, nullable=False)
    bike_trail                  =   db.Column(db.Boolean, default=False, nullable=False)
    boat_launch                 =   db.Column(db.Boolean, default=False, nullable=False)
    botanical_garden            =   db.Column(db.Boolean, default=False, nullable=False)
    bridge                      =   db.Column(db.Boolean, default=False, nullable=False)
    campground                  =   db.Column(db.Boolean, default=False, nullable=False)
    canal_lock                  =   db.Column(db.Boolean, default=False, nullable=False)
    canal                       =   db.Column(db.Boolean, default=False, nullable=False)
    castle                      =   db.Column(db.Boolean, default=False, nullable=False)
    cave                        =   db.Column(db.Boolean, default=False, nullable=False)
    cemetery                    =   db.Column(db.Boolean, default=False, nullable=False)
    dam                         =   db.Column(db.Boolean, default=False, nullable=False)
    dive_spot                   =   db.Column(db.Boolean, default=False, nullable=False)
    dog_run                     =   db.Column(db.Boolean, default=False, nullable=False)
    farm                        =   db.Column(db.Boolean, default=False, nullable=False)
    field                       =   db.Column(db.Boolean, default=False, nullable=False)
    fishing_spot                =   db.Column(db.Boolean, default=False, nullable=False)
    forest                      =   db.Column(db.Boolean, default=False, nullable=False)
    fountain                    =   db.Column(db.Boolean, default=False, nullable=False)
    garden                      =   db.Column(db.Boolean, default=False, nullable=False)
    gun_range                   =   db.Column(db.Boolean, default=False, nullable=False)
    harbor_or_marina            =   db.Column(db.Boolean, default=False, nullable=False)
    hill                        =   db.Column(db.Boolean, default=False, nullable=False)
    hot_spring                  =   db.Column(db.Boolean, default=False, nullable=False)
    indoor_play_area            =   db.Column(db.Boolean, default=False, nullable=False)
    island                      =   db.Column(db.Boolean, default=False, nullable=False)
    lake                        =   db.Column(db.Boolean, default=False, nullable=False)
    lighthouse                  =   db.Column(db.Boolean, default=False, nullable=False)
    mountain_hut                =   db.Column(db.Boolean, default=False, nullable=False)
    mountain                    =   db.Column(db.Boolean, default=False, nullable=False)
    national_park               =   db.Column(db.Boolean, default=False, nullable=False)
    nature_preserve             =   db.Column(db.Boolean, default=False, nullable=False)
    other_great_outdoors        =   db.Column(db.Boolean, default=False, nullable=False)
    palace                      =   db.Column(db.Boolean, default=False, nullable=False)
    park                        =   db.Column(db.Boolean, default=False, nullable=False)
    pedestrian_plaza            =   db.Column(db.Boolean, default=False, nullable=False)
    picnic_area                 =   db.Column(db.Boolean, default=False, nullable=False)
    picnic_shelter              =   db.Column(db.Boolean, default=False, nullable=False)
    playground                  =   db.Column(db.Boolean, default=False, nullable=False)
    plaza                       =   db.Column(db.Boolean, default=False, nullable=False)
    pool                        =   db.Column(db.Boolean, default=False, nullable=False)
    rafting                     =   db.Column(db.Boolean, default=False, nullable=False)
    recreation_center           =   db.Column(db.Boolean, default=False, nullable=False)
    reservoir                   =   db.Column(db.Boolean, default=False, nullable=False)
    river                       =   db.Column(db.Boolean, default=False, nullable=False)
    rock_climbing_spot          =   db.Column(db.Boolean, default=False, nullable=False)
    roof_deck                   =   db.Column(db.Boolean, default=False, nullable=False)
    scenic_lookout              =   db.Column(db.Boolean, default=False, nullable=False)
    sculpture_garden            =   db.Column(db.Boolean, default=False, nullable=False)
    ski_area                    =   db.Column(db.Boolean, default=False, nullable=False)
    skydiving_drop_zone         =   db.Column(db.Boolean, default=False, nullable=False)
    stables                     =   db.Column(db.Boolean, default=False, nullable=False)
    state_or_provincial_park    =   db.Column(db.Boolean, default=False, nullable=False)
    states_and_municipalities   =   db.Column(db.Boolean, default=False, nullable=False)
    summer_camp                 =   db.Column(db.Boolean, default=False, nullable=False)
    trail                       =   db.Column(db.Boolean, default=False, nullable=False)
    tree                        =   db.Column(db.Boolean, default=False, nullable=False)
    vineyard                    =   db.Column(db.Boolean, default=False, nullable=False)
    volcano                     =   db.Column(db.Boolean, default=False, nullable=False)
    waterfall                   =   db.Column(db.Boolean, default=False, nullable=False)
    waterfront                  =   db.Column(db.Boolean, default=False, nullable=False)
    well                        =   db.Column(db.Boolean, default=False, nullable=False)
    windmill                    =   db.Column(db.Boolean, default=False, nullable=False)

class   ProfessionalAndOtherPlaces(db.Model):
    user_id                 =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    animal_shelter          =   db.Column(db.Boolean, default=False, nullable=False)
    architecture_firm       =   db.Column(db.Boolean, default=False, nullable=False)
    art_studio              =   db.Column(db.Boolean, default=False, nullable=False)
    auditorium              =   db.Column(db.Boolean, default=False, nullable=False)
    ballroom                =   db.Column(db.Boolean, default=False, nullable=False)
    building                =   db.Column(db.Boolean, default=False, nullable=False)
    business_center         =   db.Column(db.Boolean, default=False, nullable=False)
    cidery                  =   db.Column(db.Boolean, default=False, nullable=False)
    club_house              =   db.Column(db.Boolean, default=False, nullable=False)
    community_center        =   db.Column(db.Boolean, default=False, nullable=False)
    convention_center       =   db.Column(db.Boolean, default=False, nullable=False)
    cultural_center         =   db.Column(db.Boolean, default=False, nullable=False)
    distillery              =   db.Column(db.Boolean, default=False, nullable=False)
    distribution_center     =   db.Column(db.Boolean, default=False, nullable=False)
    event_space             =   db.Column(db.Boolean, default=False, nullable=False)
    factory                 =   db.Column(db.Boolean, default=False, nullable=False)
    fair                    =   db.Column(db.Boolean, default=False, nullable=False)
    funeral_home            =   db.Column(db.Boolean, default=False, nullable=False)
    government_building     =   db.Column(db.Boolean, default=False, nullable=False)
    industrial_estate       =   db.Column(db.Boolean, default=False, nullable=False)
    library                 =   db.Column(db.Boolean, default=False, nullable=False)
    meadery                 =   db.Column(db.Boolean, default=False, nullable=False)
    medical_center          =   db.Column(db.Boolean, default=False, nullable=False)
    military_base           =   db.Column(db.Boolean, default=False, nullable=False)
    non_profit              =   db.Column(db.Boolean, default=False, nullable=False)
    observatory             =   db.Column(db.Boolean, default=False, nullable=False)
    office                  =   db.Column(db.Boolean, default=False, nullable=False)
    parking                 =   db.Column(db.Boolean, default=False, nullable=False)
    post_office             =   db.Column(db.Boolean, default=False, nullable=False)
    power_plant             =   db.Column(db.Boolean, default=False, nullable=False)
    prison                  =   db.Column(db.Boolean, default=False, nullable=False)
    radio_station           =   db.Column(db.Boolean, default=False, nullable=False)
    recruiting_agency       =   db.Column(db.Boolean, default=False, nullable=False)
    research_laboratory     =   db.Column(db.Boolean, default=False, nullable=False)
    research_station        =   db.Column(db.Boolean, default=False, nullable=False)
    school                  =   db.Column(db.Boolean, default=False, nullable=False)
    social_club             =   db.Column(db.Boolean, default=False, nullable=False)
    spiritual_center        =   db.Column(db.Boolean, default=False, nullable=False)
    tv_station              =   db.Column(db.Boolean, default=False, nullable=False)
    voting_booth            =   db.Column(db.Boolean, default=False, nullable=False)
    warehouse               =   db.Column(db.Boolean, default=False, nullable=False)
    waste_facility          =   db.Column(db.Boolean, default=False, nullable=False)
    wedding_hall            =   db.Column(db.Boolean, default=False, nullable=False)
    winery                  =   db.Column(db.Boolean, default=False, nullable=False)

class   Residence(db.Model):
    user_id                                   =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    assisted_living                           =   db.Column(db.Boolean, default=False, nullable=False)
    home_private                              =   db.Column(db.Boolean, default=False, nullable=False)
    housing_development                       =   db.Column(db.Boolean, default=False, nullable=False)
    residential_building_apartment_or_condo   =   db.Column(db.Boolean, default=False, nullable=False)
    trailer_park                              =   db.Column(db.Boolean, default=False, nullable=False)

class   ShopAndService(db.Model):
    user_id                                     =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    atm                                         =   db.Column(db.Boolean, default=False, nullable=False)
    adult_boutique                              =   db.Column(db.Boolean, default=False, nullable=False)
    antique_shop                                =   db.Column(db.Boolean, default=False, nullable=False)
    arts_and_crafts_store                       =   db.Column(db.Boolean, default=False, nullable=False)
    astrologer                                  =   db.Column(db.Boolean, default=False, nullable=False)
    auto_dealership                             =   db.Column(db.Boolean, default=False, nullable=False)
    auto_garage                                 =   db.Column(db.Boolean, default=False, nullable=False)
    auto_workshop                               =   db.Column(db.Boolean, default=False, nullable=False)
    automotive_shop                             =   db.Column(db.Boolean, default=False, nullable=False)
    baby_store                                  =   db.Column(db.Boolean, default=False, nullable=False)
    bank                                        =   db.Column(db.Boolean, default=False, nullable=False)
    bath_house                                  =   db.Column(db.Boolean, default=False, nullable=False)
    batik_shop                                  =   db.Column(db.Boolean, default=False, nullable=False)
    betting_shop                                =   db.Column(db.Boolean, default=False, nullable=False)
    big_box_store                               =   db.Column(db.Boolean, default=False, nullable=False)
    bike_shop                                   =   db.Column(db.Boolean, default=False, nullable=False)
    board_shop                                  =   db.Column(db.Boolean, default=False, nullable=False)
    bookstore                                   =   db.Column(db.Boolean, default=False, nullable=False)
    bridal_shop                                 =   db.Column(db.Boolean, default=False, nullable=False)
    business_service                            =   db.Column(db.Boolean, default=False, nullable=False)
    camera_store                                =   db.Column(db.Boolean, default=False, nullable=False)
    candy_store                                 =   db.Column(db.Boolean, default=False, nullable=False)
    car_wash                                    =   db.Column(db.Boolean, default=False, nullable=False)
    carpet_store                                =   db.Column(db.Boolean, default=False, nullable=False)
    check_cashing_service                       =   db.Column(db.Boolean, default=False, nullable=False)
    child_care_service                          =   db.Column(db.Boolean, default=False, nullable=False)
    chocolate_shop                              =   db.Column(db.Boolean, default=False, nullable=False)
    clothing_store                              =   db.Column(db.Boolean, default=False, nullable=False)
    comic_shop                                  =   db.Column(db.Boolean, default=False, nullable=False)
    construction_and_landscaping                =   db.Column(db.Boolean, default=False, nullable=False)
    convenience_store                           =   db.Column(db.Boolean, default=False, nullable=False)
    cosmetics_shop                              =   db.Column(db.Boolean, default=False, nullable=False)
    costume_shop                                =   db.Column(db.Boolean, default=False, nullable=False)
    credit_union                                =   db.Column(db.Boolean, default=False, nullable=False)
    currency_exchange                           =   db.Column(db.Boolean, default=False, nullable=False)
    department_store                            =   db.Column(db.Boolean, default=False, nullable=False)
    design_studio                               =   db.Column(db.Boolean, default=False, nullable=False)
    discount_store                              =   db.Column(db.Boolean, default=False, nullable=False)
    dive_shop                                   =   db.Column(db.Boolean, default=False, nullable=False)
    drugstore                                   =   db.Column(db.Boolean, default=False, nullable=False)
    dry_cleaner                                 =   db.Column(db.Boolean, default=False, nullable=False)
    ev_charging_station                         =   db.Column(db.Boolean, default=False, nullable=False)
    electronics_store                           =   db.Column(db.Boolean, default=False, nullable=False)
    entertainment_service                       =   db.Column(db.Boolean, default=False, nullable=False)
    event_service                               =   db.Column(db.Boolean, default=False, nullable=False)
    fabric_shop                                 =   db.Column(db.Boolean, default=False, nullable=False)
    film_studio                                 =   db.Column(db.Boolean, default=False, nullable=False)
    financial_or_legal_service      =   db.Column(db.Boolean, default=False, nullable=False)
    fireworks_store      =   db.Column(db.Boolean, default=False, nullable=False)
    fishing_store      =   db.Column(db.Boolean, default=False, nullable=False)
    flea_market      =   db.Column(db.Boolean, default=False, nullable=False)
    floating_market      =   db.Column(db.Boolean, default=False, nullable=False)
    flower_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    food_and_drink_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    frame_store      =   db.Column(db.Boolean, default=False, nullable=False)
    fruit_and_vegetable_store      =   db.Column(db.Boolean, default=False, nullable=False)
    furniture_or_home_store      =   db.Column(db.Boolean, default=False, nullable=False)
    gaming_cafe      =   db.Column(db.Boolean, default=False, nullable=False)
    garden_center      =   db.Column(db.Boolean, default=False, nullable=False)
    gas_station      =   db.Column(db.Boolean, default=False, nullable=False)
    gift_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    gun_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    hardware_store      =   db.Column(db.Boolean, default=False, nullable=False)
    health_and_beauty_service      =   db.Column(db.Boolean, default=False, nullable=False)
    herbs_and_spices_store      =   db.Column(db.Boolean, default=False, nullable=False)
    hobby_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    home_service      =   db.Column(db.Boolean, default=False, nullable=False)
    hunting_supply      =   db.Column(db.Boolean, default=False, nullable=False)
    it_services      =   db.Column(db.Boolean, default=False, nullable=False)
    insurance_office      =   db.Column(db.Boolean, default=False, nullable=False)
    internet_cafe      =   db.Column(db.Boolean, default=False, nullable=False)
    jewelry_store      =   db.Column(db.Boolean, default=False, nullable=False)
    kitchen_supply_store      =   db.Column(db.Boolean, default=False, nullable=False)
    knitting_store      =   db.Column(db.Boolean, default=False, nullable=False)
    laundromat      =   db.Column(db.Boolean, default=False, nullable=False)
    laundry_service      =   db.Column(db.Boolean, default=False, nullable=False)
    lawyer      =   db.Column(db.Boolean, default=False, nullable=False)
    leather_goods_store      =   db.Column(db.Boolean, default=False, nullable=False)
    locksmith      =   db.Column(db.Boolean, default=False, nullable=False)
    lottery_retailer      =   db.Column(db.Boolean, default=False, nullable=False)
    luggage_store      =   db.Column(db.Boolean, default=False, nullable=False)
    marijuana_dispensary      =   db.Column(db.Boolean, default=False, nullable=False)
    market      =   db.Column(db.Boolean, default=False, nullable=False)
    massage_studio      =   db.Column(db.Boolean, default=False, nullable=False)
    mattress_store      =   db.Column(db.Boolean, default=False, nullable=False)
    medical_supply_store      =   db.Column(db.Boolean, default=False, nullable=False)
    miscellaneous_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    mobile_phone_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    mobility_store      =   db.Column(db.Boolean, default=False, nullable=False)
    motorcycle_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    motorsports_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    music_store      =   db.Column(db.Boolean, default=False, nullable=False)
    nail_salon      =   db.Column(db.Boolean, default=False, nullable=False)
    newsagent      =   db.Column(db.Boolean, default=False, nullable=False)
    newsstand      =   db.Column(db.Boolean, default=False, nullable=False)
    notary      =   db.Column(db.Boolean, default=False, nullable=False)
    optical_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    other_repair_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    outdoor_supply_store      =   db.Column(db.Boolean, default=False, nullable=False)
    outlet_mall      =   db.Column(db.Boolean, default=False, nullable=False)
    outlet_store      =   db.Column(db.Boolean, default=False, nullable=False)
    paper_or_office_supplies_store      =   db.Column(db.Boolean, default=False, nullable=False)
    pawn_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    perfume_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    pet_service      =   db.Column(db.Boolean, default=False, nullable=False)
    pet_store      =   db.Column(db.Boolean, default=False, nullable=False)
    pharmacy      =   db.Column(db.Boolean, default=False, nullable=False)
    photography_lab      =   db.Column(db.Boolean, default=False, nullable=False)
    photography_studio      =   db.Column(db.Boolean, default=False, nullable=False)
    piercing_parlor      =   db.Column(db.Boolean, default=False, nullable=False)
    pop_up_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    print_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    public_bathroom      =   db.Column(db.Boolean, default=False, nullable=False)
    real_estate_office      =   db.Column(db.Boolean, default=False, nullable=False)
    record_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    recording_studio      =   db.Column(db.Boolean, default=False, nullable=False)
    recycling_facility      =   db.Column(db.Boolean, default=False, nullable=False)
    rental_service      =   db.Column(db.Boolean, default=False, nullable=False)
    salon_or_barbershop      =   db.Column(db.Boolean, default=False, nullable=False)
    sauna_or_steam_room      =   db.Column(db.Boolean, default=False, nullable=False)
    shipping_store      =   db.Column(db.Boolean, default=False, nullable=False)
    shoe_repair      =   db.Column(db.Boolean, default=False, nullable=False)
    shopping_mall      =   db.Column(db.Boolean, default=False, nullable=False)
    shopping_plaza      =   db.Column(db.Boolean, default=False, nullable=False)
    skate_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    ski_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    smoke_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    smoothie_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    souvenir_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    spa      =   db.Column(db.Boolean, default=False, nullable=False)
    sporting_goods_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    stationery_store      =   db.Column(db.Boolean, default=False, nullable=False)
    storage_facility      =   db.Column(db.Boolean, default=False, nullable=False)
    supplement_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    tailor_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    tanning_salon      =   db.Column(db.Boolean, default=False, nullable=False)
    tattoo_parlor      =   db.Column(db.Boolean, default=False, nullable=False)
    thrift_or_vintage_store      =   db.Column(db.Boolean, default=False, nullable=False)
    toy_or_game_store      =   db.Column(db.Boolean, default=False, nullable=False)
    travel_agency      =   db.Column(db.Boolean, default=False, nullable=False)
    used_bookstore      =   db.Column(db.Boolean, default=False, nullable=False)
    vape_store      =   db.Column(db.Boolean, default=False, nullable=False)
    vehicle_inspection_station      =   db.Column(db.Boolean, default=False, nullable=False)
    video_game_store      =   db.Column(db.Boolean, default=False, nullable=False)
    video_store      =   db.Column(db.Boolean, default=False, nullable=False)
    warehouse_store      =   db.Column(db.Boolean, default=False, nullable=False)
    watch_shop      =   db.Column(db.Boolean, default=False, nullable=False)

class   TravelAndTransport(db.Model):
    user_id                     =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    airport      =   db.Column(db.Boolean, default=False, nullable=False)
    baggage_locker      =   db.Column(db.Boolean, default=False, nullable=False)
    bike_rental_or_bike_share      =   db.Column(db.Boolean, default=False, nullable=False)
    boat_rental      =   db.Column(db.Boolean, default=False, nullable=False)
    boat_or_ferry      =   db.Column(db.Boolean, default=False, nullable=False)
    border_crossing      =   db.Column(db.Boolean, default=False, nullable=False)
    bus_station      =   db.Column(db.Boolean, default=False, nullable=False)
    bus_stop      =   db.Column(db.Boolean, default=False, nullable=False)
    cable_car      =   db.Column(db.Boolean, default=False, nullable=False)
    cruise_ship      =   db.Column(db.Boolean, default=False, nullable=False)
    duty_free_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    general_travel      =   db.Column(db.Boolean, default=False, nullable=False)
    heliport      =   db.Column(db.Boolean, default=False, nullable=False)
    hotel      =   db.Column(db.Boolean, default=False, nullable=False)
    intersection      =   db.Column(db.Boolean, default=False, nullable=False)
    light_rail_station      =   db.Column(db.Boolean, default=False, nullable=False)
    marine_terminal      =   db.Column(db.Boolean, default=False, nullable=False)
    metro_station      =   db.Column(db.Boolean, default=False, nullable=False)
    moving_target      =   db.Column(db.Boolean, default=False, nullable=False)
    pier      =   db.Column(db.Boolean, default=False, nullable=False)
    port      =   db.Column(db.Boolean, default=False, nullable=False)
    rv_park      =   db.Column(db.Boolean, default=False, nullable=False)
    rental_car_location      =   db.Column(db.Boolean, default=False, nullable=False)
    rest_area      =   db.Column(db.Boolean, default=False, nullable=False)
    road      =   db.Column(db.Boolean, default=False, nullable=False)
    taxi_stand      =   db.Column(db.Boolean, default=False, nullable=False)
    taxi      =   db.Column(db.Boolean, default=False, nullable=False)
    toll_booth      =   db.Column(db.Boolean, default=False, nullable=False)
    toll_plaza      =   db.Column(db.Boolean, default=False, nullable=False)
    tourist_information_center      =   db.Column(db.Boolean, default=False, nullable=False)
    train_station      =   db.Column(db.Boolean, default=False, nullable=False)
    tram_station      =   db.Column(db.Boolean, default=False, nullable=False)
    transportation_service      =   db.Column(db.Boolean, default=False, nullable=False)
    travel_lounge      =   db.Column(db.Boolean, default=False, nullable=False)
    truck_stop      =   db.Column(db.Boolean, default=False, nullable=False)
    tunnel      =   db.Column(db.Boolean, default=False, nullable=False)
    



###########################################################################################################################################################
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
###########################################################################################################################################################




# Below classes belong to Trip subsection of Database


class TripData(db.Model):
    __tablename__ = 'trip_data'
    

    user_id =    db.Column(db.Integer, nullable=False)
    trip_id =    db.Column(db.String(8) , primary_key=True, nullable=False, unique=True)
    city_name =  db.Column(db.String(100))
    start_date = db.Column(db.String(10))
    end_date = db.Column(db.String(10))
    lattitude = db.Column(db.String(10))
    longitude = db.Column(db.String(10))

class VenueData(db.Model):
    __tablename__ = 'venue_data'
    

    trip_id =    db.Column(db.String(8) , primary_key=True, nullable=False, unique=True)
    venue_id =  db.Column(db.String(900))
    lattitude =  db.Column(db.String(500))
    longitude =  db.Column(db.String(500))
    name =   db.Column(db.String(1000))
    address =   db.Column(db.String(1700))


class BudgetPlanner(db.Model):
    __tablename__ = 'budget_planner'
    
    trip_id =    db.Column(db.String(8) , primary_key=True, nullable=False, unique=True)
    expense_name =  db.Column(db.String(700))
    expense_value =  db.Column(db.String(400))


class UserCategoryTrip(db.Model):
    __tablename__ = 'user_category_trip'
    
    user_id                         =   db.Column(db.String(8), nullable=False)
    trip_id                         =   db.Column(db.String(8) , primary_key=True, nullable=False, unique=True)
    art_and_entertainment           =   db.Column(db.Boolean, default=False, nullable=False)
    college_and_university          =   db.Column(db.Boolean, default=False, nullable=False)
    event                           =   db.Column(db.Boolean, default=False, nullable=False)
    food                            =   db.Column(db.Boolean, default=False, nullable=False)
    nightlife_spot                  =   db.Column(db.Boolean, default=False, nullable=False)
    outdoors_and_recreation         =   db.Column(db.Boolean, default=False, nullable=False)
    professional_and_other_places   =   db.Column(db.Boolean, default=False, nullable=False)
    residence                       =   db.Column(db.Boolean, default=False, nullable=False)
    shop_and_service                =   db.Column(db.Boolean, default=False, nullable=False)
    travel_and_transport            =   db.Column(db.Boolean, default=False, nullable=False)

class ArtAndEntertainmentTrip(db.Model):

    __tablename__ = 'art_and_entertainment_trip'
    


    user_id                         =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    amphitheater                    =   db.Column(db.Boolean, default=False, nullable=False)
    aquarium                        =   db.Column(db.Boolean, default=False, nullable=False)
    arcade                          =   db.Column(db.Boolean, default=False, nullable=False)
    art_gallery                     =   db.Column(db.Boolean, default=False, nullable=False)
    bowling_alley                   =   db.Column(db.Boolean, default=False, nullable=False)
    casino                          =   db.Column(db.Boolean, default=False, nullable=False)
    circus                          =   db.Column(db.Boolean, default=False, nullable=False)
    comedy_club                     =   db.Column(db.Boolean, default=False, nullable=False)
    concert_hall                    =   db.Column(db.Boolean, default=False, nullable=False)
    country_dance_club              =   db.Column(db.Boolean, default=False, nullable=False)
    disc_golf                       =   db.Column(db.Boolean, default=False, nullable=False)
    escape_room                     =   db.Column(db.Boolean, default=False, nullable=False)
    exhibit                         =   db.Column(db.Boolean, default=False, nullable=False)
    general_entertainment           =   db.Column(db.Boolean, default=False, nullable=False)
    go_kart_track                   =   db.Column(db.Boolean, default=False, nullable=False)
    historic_site                   =   db.Column(db.Boolean, default=False, nullable=False)
    karaoke_box                     =   db.Column(db.Boolean, default=False, nullable=False)
    laser_tag                       =   db.Column(db.Boolean, default=False, nullable=False)
    memorial_site                   =   db.Column(db.Boolean, default=False, nullable=False)
    mini_golf                       =   db.Column(db.Boolean, default=False, nullable=False)
    movie_theater                   =   db.Column(db.Boolean, default=False, nullable=False)
    museum                          =   db.Column(db.Boolean, default=False, nullable=False)
    music_venue                     =   db.Column(db.Boolean, default=False, nullable=False)
    pachinko_parlor                 =   db.Column(db.Boolean, default=False, nullable=False)
    performing_arts_venue           =   db.Column(db.Boolean, default=False, nullable=False)
    pool_hall                       =   db.Column(db.Boolean, default=False, nullable=False)
    public_art                      =   db.Column(db.Boolean, default=False, nullable=False)
    racecourse                      =   db.Column(db.Boolean, default=False, nullable=False)
    racetrack                       =   db.Column(db.Boolean, default=False, nullable=False)
    roller_rink                     =   db.Column(db.Boolean, default=False, nullable=False)
    salsa_club                      =   db.Column(db.Boolean, default=False, nullable=False)
    samba_school                    =   db.Column(db.Boolean, default=False, nullable=False)
    stadium                         =   db.Column(db.Boolean, default=False, nullable=False)
    theme_park                      =   db.Column(db.Boolean, default=False, nullable=False)
    tour_provider                   =   db.Column(db.Boolean, default=False, nullable=False)
    vr_cafe                         =   db.Column(db.Boolean, default=False, nullable=False)
    water_park                      =   db.Column(db.Boolean, default=False, nullable=False)
    zoo                             =   db.Column(db.Boolean, default=False, nullable=False)

class CollegeAndUniversityTrip(db.Model):

    __tablename__ = 'college_and_university_trip'
    

    user_id                          =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    college_academic_building        =   db.Column(db.Boolean, default=False, nullable=False)
    college_administrative_building  =   db.Column(db.Boolean, default=False, nullable=False)
    college_auditorium               =   db.Column(db.Boolean, default=False, nullable=False)
    college_bookstore                =   db.Column(db.Boolean, default=False, nullable=False)
    college_cafeteria                =   db.Column(db.Boolean, default=False, nullable=False)
    college_classroom                =   db.Column(db.Boolean, default=False, nullable=False)
    college_gym                      =   db.Column(db.Boolean, default=False, nullable=False)
    college_lab                      =   db.Column(db.Boolean, default=False, nullable=False)
    college_library                  =   db.Column(db.Boolean, default=False, nullable=False)
    college_quad                     =   db.Column(db.Boolean, default=False, nullable=False)
    college_rec_center               =   db.Column(db.Boolean, default=False, nullable=False)
    college_residence_hall           =   db.Column(db.Boolean, default=False, nullable=False)
    college_stadium                  =   db.Column(db.Boolean, default=False, nullable=False)
    college_theater                  =   db.Column(db.Boolean, default=False, nullable=False)
    community_college                =   db.Column(db.Boolean, default=False, nullable=False)
    fraternity_house                 =   db.Column(db.Boolean, default=False, nullable=False)
    general_college_and_university   =   db.Column(db.Boolean, default=False, nullable=False)
    law_school                       =   db.Column(db.Boolean, default=False, nullable=False)
    medical_school                   =   db.Column(db.Boolean, default=False, nullable=False)
    sorority_house                   =   db.Column(db.Boolean, default=False, nullable=False)
    student_center                   =   db.Column(db.Boolean, default=False, nullable=False)
    trade_school                     =   db.Column(db.Boolean, default=False, nullable=False)
    university                       =   db.Column(db.Boolean, default=False, nullable=False)

class EventTrip(db.Model):

    __tablename__ = 'event_trip'
    

    user_id             =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    christmas_market    =   db.Column(db.Boolean, default=False, nullable=False)
    conference          =   db.Column(db.Boolean, default=False, nullable=False)
    convention          =   db.Column(db.Boolean, default=False, nullable=False)
    festival            =   db.Column(db.Boolean, default=False, nullable=False)
    line_or_queue       =   db.Column(db.Boolean, default=False, nullable=False)
    music_festival      =   db.Column(db.Boolean, default=False, nullable=False)
    other_event         =   db.Column(db.Boolean, default=False, nullable=False)
    parade              =   db.Column(db.Boolean, default=False, nullable=False)
    sporting_event      =   db.Column(db.Boolean, default=False, nullable=False)
    stoop_sale          =   db.Column(db.Boolean, default=False, nullable=False)
    street_fair         =   db.Column(db.Boolean, default=False, nullable=False)
    trade_fair          =   db.Column(db.Boolean, default=False, nullable=False)

class FoodTrip(db.Model):

    __tablename__ = 'food_trip'
    

    user_id                                    =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    afghan_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    african_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    american_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    armenian_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    asian_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    australian_restaurant                      =   db.Column(db.Boolean, default=False, nullable=False)
    austrian_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    bbq_joint                                  =   db.Column(db.Boolean, default=False, nullable=False)
    bagel_shop                                 =   db.Column(db.Boolean, default=False, nullable=False)
    bakery                                     =   db.Column(db.Boolean, default=False, nullable=False)
    bangladeshi_restaurant                     =   db.Column(db.Boolean, default=False, nullable=False)
    belgian_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    bistro                                     =   db.Column(db.Boolean, default=False, nullable=False)
    breakfast_spot                             =   db.Column(db.Boolean, default=False, nullable=False)
    bubble_tea_shop                            =   db.Column(db.Boolean, default=False, nullable=False)
    buffet                                     =   db.Column(db.Boolean, default=False, nullable=False)
    burger_joint                               =   db.Column(db.Boolean, default=False, nullable=False)
    cafeteria                                  =   db.Column(db.Boolean, default=False, nullable=False)
    café                                       =   db.Column(db.Boolean, default=False, nullable=False)
    cajun_or_creole_restaurant                 =   db.Column(db.Boolean, default=False, nullable=False)
    caribbean_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    caucasian_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    coffee_shop                                =   db.Column(db.Boolean, default=False, nullable=False)
    comfort_food_restaurant                    =   db.Column(db.Boolean, default=False, nullable=False)
    creperie                                   =   db.Column(db.Boolean, default=False, nullable=False)
    czech_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    deli_or_bodega                             =   db.Column(db.Boolean, default=False, nullable=False)
    dessert_shop                               =   db.Column(db.Boolean, default=False, nullable=False)
    diner                                      =   db.Column(db.Boolean, default=False, nullable=False)
    donut_shop                                 =   db.Column(db.Boolean, default=False, nullable=False)
    dumpling_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    dutch_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    eastern_european_restaurant                =   db.Column(db.Boolean, default=False, nullable=False)
    english_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    falafel_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    fast_food_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    fish_and_chips_shop                        =   db.Column(db.Boolean, default=False, nullable=False)
    fondue_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    food_court                                 =   db.Column(db.Boolean, default=False, nullable=False)
    food_stand                                 =   db.Column(db.Boolean, default=False, nullable=False)
    food_truck                                 =   db.Column(db.Boolean, default=False, nullable=False)
    french_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    fried_chicken_joint                        =   db.Column(db.Boolean, default=False, nullable=False)
    friterie                                   =   db.Column(db.Boolean, default=False, nullable=False)
    gastropub                                  =   db.Column(db.Boolean, default=False, nullable=False)
    german_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    gluten_free_restaurant                     =   db.Column(db.Boolean, default=False, nullable=False)
    greek_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    halal_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    hawaiian_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    hot_dog_joint                              =   db.Column(db.Boolean, default=False, nullable=False)
    hungarian_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    indian_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    irish_pub                                  =   db.Column(db.Boolean, default=False, nullable=False)
    italian_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    jewish_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    juice_bar                                  =   db.Column(db.Boolean, default=False, nullable=False)
    kebab_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    latin_american_restaurant                  =   db.Column(db.Boolean, default=False, nullable=False)
    mac_and_cheese_joint                       =   db.Column(db.Boolean, default=False, nullable=False)
    mediterranean_restaurant                   =   db.Column(db.Boolean, default=False, nullable=False)
    mexican_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    middle_eastern_restaurant                  =   db.Column(db.Boolean, default=False, nullable=False)
    modern_european_restaurant                 =   db.Column(db.Boolean, default=False, nullable=False)
    molecular_gastronomy_restaurant            =   db.Column(db.Boolean, default=False, nullable=False)
    pakistani_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    pet_café                                   =   db.Column(db.Boolean, default=False, nullable=False)
    pizza_place                                =   db.Column(db.Boolean, default=False, nullable=False)
    polish_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    portuguese_restaurant                      =   db.Column(db.Boolean, default=False, nullable=False)
    poutine_place                              =   db.Column(db.Boolean, default=False, nullable=False)
    restaurant                                 =   db.Column(db.Boolean, default=False, nullable=False)
    russian_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    salad_place                                =   db.Column(db.Boolean, default=False, nullable=False)
    sandwich_place                             =   db.Column(db.Boolean, default=False, nullable=False)
    scandinavian_restaurant                    =   db.Column(db.Boolean, default=False, nullable=False)
    scottish_restaurant                        =   db.Column(db.Boolean, default=False, nullable=False)
    seafood_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    slovak_restaurant                          =   db.Column(db.Boolean, default=False, nullable=False)
    snack_place                                =   db.Column(db.Boolean, default=False, nullable=False)
    soup_place                                 =   db.Column(db.Boolean, default=False, nullable=False)
    southern_or_soul_food_restaurant           =   db.Column(db.Boolean, default=False, nullable=False)
    spanish_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    sri_lankan_restaurant                      =   db.Column(db.Boolean, default=False, nullable=False)
    steakhouse                                 =   db.Column(db.Boolean, default=False, nullable=False)
    swiss_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    tea_room                                   =   db.Column(db.Boolean, default=False, nullable=False)
    theme_restaurant                           =   db.Column(db.Boolean, default=False, nullable=False)
    turkish_restaurant                         =   db.Column(db.Boolean, default=False, nullable=False)
    ukrainian_restaurant                       =   db.Column(db.Boolean, default=False, nullable=False)
    vegetarian_or_vegan_restaurant             =   db.Column(db.Boolean, default=False, nullable=False)
    wings_joint                                =   db.Column(db.Boolean, default=False, nullable=False)

class   NightlifeSpotTrip(db.Model):

    __tablename__ = 'nightlife_spot_trip'
    

    user_id                     =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    bar                         =   db.Column(db.Boolean, default=False, nullable=False)
    brewery                     =   db.Column(db.Boolean, default=False, nullable=False)
    lounge                      =   db.Column(db.Boolean, default=False, nullable=False)
    night_market                =   db.Column(db.Boolean, default=False, nullable=False)
    nightclub                   =   db.Column(db.Boolean, default=False, nullable=False)
    other_nightlife             =   db.Column(db.Boolean, default=False, nullable=False)
    strip_club                  =   db.Column(db.Boolean, default=False, nullable=False)


class OutdoorsAndRecreationTrip(db.Model):

    __tablename__ = 'outdoors_and_recreation_trip'
    

    user_id                     =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    athletics_and_sports        =   db.Column(db.Boolean, default=False, nullable=False)
    bathing_area                =   db.Column(db.Boolean, default=False, nullable=False)
    bay                         =   db.Column(db.Boolean, default=False, nullable=False)
    beach                       =   db.Column(db.Boolean, default=False, nullable=False)
    bike_trail                  =   db.Column(db.Boolean, default=False, nullable=False)
    boat_launch                 =   db.Column(db.Boolean, default=False, nullable=False)
    botanical_garden            =   db.Column(db.Boolean, default=False, nullable=False)
    bridge                      =   db.Column(db.Boolean, default=False, nullable=False)
    campground                  =   db.Column(db.Boolean, default=False, nullable=False)
    canal_lock                  =   db.Column(db.Boolean, default=False, nullable=False)
    canal                       =   db.Column(db.Boolean, default=False, nullable=False)
    castle                      =   db.Column(db.Boolean, default=False, nullable=False)
    cave                        =   db.Column(db.Boolean, default=False, nullable=False)
    cemetery                    =   db.Column(db.Boolean, default=False, nullable=False)
    dam                         =   db.Column(db.Boolean, default=False, nullable=False)
    dive_spot                   =   db.Column(db.Boolean, default=False, nullable=False)
    dog_run                     =   db.Column(db.Boolean, default=False, nullable=False)
    farm                        =   db.Column(db.Boolean, default=False, nullable=False)
    field                       =   db.Column(db.Boolean, default=False, nullable=False)
    fishing_spot                =   db.Column(db.Boolean, default=False, nullable=False)
    forest                      =   db.Column(db.Boolean, default=False, nullable=False)
    fountain                    =   db.Column(db.Boolean, default=False, nullable=False)
    garden                      =   db.Column(db.Boolean, default=False, nullable=False)
    gun_range                   =   db.Column(db.Boolean, default=False, nullable=False)
    harbor_or_marina            =   db.Column(db.Boolean, default=False, nullable=False)
    hill                        =   db.Column(db.Boolean, default=False, nullable=False)
    hot_spring                  =   db.Column(db.Boolean, default=False, nullable=False)
    indoor_play_area            =   db.Column(db.Boolean, default=False, nullable=False)
    island                      =   db.Column(db.Boolean, default=False, nullable=False)
    lake                        =   db.Column(db.Boolean, default=False, nullable=False)
    lighthouse                  =   db.Column(db.Boolean, default=False, nullable=False)
    mountain_hut                =   db.Column(db.Boolean, default=False, nullable=False)
    mountain                    =   db.Column(db.Boolean, default=False, nullable=False)
    national_park               =   db.Column(db.Boolean, default=False, nullable=False)
    nature_preserve             =   db.Column(db.Boolean, default=False, nullable=False)
    other_great_outdoors        =   db.Column(db.Boolean, default=False, nullable=False)
    palace                      =   db.Column(db.Boolean, default=False, nullable=False)
    park                        =   db.Column(db.Boolean, default=False, nullable=False)
    pedestrian_plaza            =   db.Column(db.Boolean, default=False, nullable=False)
    picnic_area                 =   db.Column(db.Boolean, default=False, nullable=False)
    picnic_shelter              =   db.Column(db.Boolean, default=False, nullable=False)
    playground                  =   db.Column(db.Boolean, default=False, nullable=False)
    plaza                       =   db.Column(db.Boolean, default=False, nullable=False)
    pool                        =   db.Column(db.Boolean, default=False, nullable=False)
    rafting                     =   db.Column(db.Boolean, default=False, nullable=False)
    recreation_center           =   db.Column(db.Boolean, default=False, nullable=False)
    reservoir                   =   db.Column(db.Boolean, default=False, nullable=False)
    river                       =   db.Column(db.Boolean, default=False, nullable=False)
    rock_climbing_spot          =   db.Column(db.Boolean, default=False, nullable=False)
    roof_deck                   =   db.Column(db.Boolean, default=False, nullable=False)
    scenic_lookout              =   db.Column(db.Boolean, default=False, nullable=False)
    sculpture_garden            =   db.Column(db.Boolean, default=False, nullable=False)
    ski_area                    =   db.Column(db.Boolean, default=False, nullable=False)
    skydiving_drop_zone         =   db.Column(db.Boolean, default=False, nullable=False)
    stables                     =   db.Column(db.Boolean, default=False, nullable=False)
    state_or_provincial_park    =   db.Column(db.Boolean, default=False, nullable=False)
    states_and_municipalities   =   db.Column(db.Boolean, default=False, nullable=False)
    summer_camp                 =   db.Column(db.Boolean, default=False, nullable=False)
    trail                       =   db.Column(db.Boolean, default=False, nullable=False)
    tree                        =   db.Column(db.Boolean, default=False, nullable=False)
    vineyard                    =   db.Column(db.Boolean, default=False, nullable=False)
    volcano                     =   db.Column(db.Boolean, default=False, nullable=False)
    waterfall                   =   db.Column(db.Boolean, default=False, nullable=False)
    waterfront                  =   db.Column(db.Boolean, default=False, nullable=False)
    well                        =   db.Column(db.Boolean, default=False, nullable=False)
    windmill                    =   db.Column(db.Boolean, default=False, nullable=False)

class   ProfessionalAndOtherPlacesTrip(db.Model):

    __tablename__ = 'professional_and_other_places_trip'
    

    user_id                 =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    animal_shelter          =   db.Column(db.Boolean, default=False, nullable=False)
    architecture_firm       =   db.Column(db.Boolean, default=False, nullable=False)
    art_studio              =   db.Column(db.Boolean, default=False, nullable=False)
    auditorium              =   db.Column(db.Boolean, default=False, nullable=False)
    ballroom                =   db.Column(db.Boolean, default=False, nullable=False)
    building                =   db.Column(db.Boolean, default=False, nullable=False)
    business_center         =   db.Column(db.Boolean, default=False, nullable=False)
    cidery                  =   db.Column(db.Boolean, default=False, nullable=False)
    club_house              =   db.Column(db.Boolean, default=False, nullable=False)
    community_center        =   db.Column(db.Boolean, default=False, nullable=False)
    convention_center       =   db.Column(db.Boolean, default=False, nullable=False)
    cultural_center         =   db.Column(db.Boolean, default=False, nullable=False)
    distillery              =   db.Column(db.Boolean, default=False, nullable=False)
    distribution_center     =   db.Column(db.Boolean, default=False, nullable=False)
    event_space             =   db.Column(db.Boolean, default=False, nullable=False)
    factory                 =   db.Column(db.Boolean, default=False, nullable=False)
    fair                    =   db.Column(db.Boolean, default=False, nullable=False)
    funeral_home            =   db.Column(db.Boolean, default=False, nullable=False)
    government_building     =   db.Column(db.Boolean, default=False, nullable=False)
    industrial_estate       =   db.Column(db.Boolean, default=False, nullable=False)
    library                 =   db.Column(db.Boolean, default=False, nullable=False)
    meadery                 =   db.Column(db.Boolean, default=False, nullable=False)
    medical_center          =   db.Column(db.Boolean, default=False, nullable=False)
    military_base           =   db.Column(db.Boolean, default=False, nullable=False)
    non_profit              =   db.Column(db.Boolean, default=False, nullable=False)
    observatory             =   db.Column(db.Boolean, default=False, nullable=False)
    office                  =   db.Column(db.Boolean, default=False, nullable=False)
    parking                 =   db.Column(db.Boolean, default=False, nullable=False)
    post_office             =   db.Column(db.Boolean, default=False, nullable=False)
    power_plant             =   db.Column(db.Boolean, default=False, nullable=False)
    prison                  =   db.Column(db.Boolean, default=False, nullable=False)
    radio_station           =   db.Column(db.Boolean, default=False, nullable=False)
    recruiting_agency       =   db.Column(db.Boolean, default=False, nullable=False)
    research_laboratory     =   db.Column(db.Boolean, default=False, nullable=False)
    research_station        =   db.Column(db.Boolean, default=False, nullable=False)
    school                  =   db.Column(db.Boolean, default=False, nullable=False)
    social_club             =   db.Column(db.Boolean, default=False, nullable=False)
    spiritual_center        =   db.Column(db.Boolean, default=False, nullable=False)
    tv_station              =   db.Column(db.Boolean, default=False, nullable=False)
    voting_booth            =   db.Column(db.Boolean, default=False, nullable=False)
    warehouse               =   db.Column(db.Boolean, default=False, nullable=False)
    waste_facility          =   db.Column(db.Boolean, default=False, nullable=False)
    wedding_hall            =   db.Column(db.Boolean, default=False, nullable=False)
    winery                  =   db.Column(db.Boolean, default=False, nullable=False)

class   ResidenceTrip(db.Model):

    __tablename__ = 'residence_trip'
    

    user_id                                   =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    assisted_living                           =   db.Column(db.Boolean, default=False, nullable=False)
    home_private                              =   db.Column(db.Boolean, default=False, nullable=False)
    housing_development                       =   db.Column(db.Boolean, default=False, nullable=False)
    residential_building_apartment_or_condo   =   db.Column(db.Boolean, default=False, nullable=False)
    trailer_park                              =   db.Column(db.Boolean, default=False, nullable=False)

class   ShopAndServiceTrip(db.Model):

    __tablename__ = 'shop_and_service_trip'
    

    user_id                                     =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    atm                                         =   db.Column(db.Boolean, default=False, nullable=False)
    adult_boutique                              =   db.Column(db.Boolean, default=False, nullable=False)
    antique_shop                                =   db.Column(db.Boolean, default=False, nullable=False)
    arts_and_crafts_store                       =   db.Column(db.Boolean, default=False, nullable=False)
    astrologer                                  =   db.Column(db.Boolean, default=False, nullable=False)
    auto_dealership                             =   db.Column(db.Boolean, default=False, nullable=False)
    auto_garage                                 =   db.Column(db.Boolean, default=False, nullable=False)
    auto_workshop                               =   db.Column(db.Boolean, default=False, nullable=False)
    automotive_shop                             =   db.Column(db.Boolean, default=False, nullable=False)
    baby_store                                  =   db.Column(db.Boolean, default=False, nullable=False)
    bank                                        =   db.Column(db.Boolean, default=False, nullable=False)
    bath_house                                  =   db.Column(db.Boolean, default=False, nullable=False)
    batik_shop                                  =   db.Column(db.Boolean, default=False, nullable=False)
    betting_shop                                =   db.Column(db.Boolean, default=False, nullable=False)
    big_box_store                               =   db.Column(db.Boolean, default=False, nullable=False)
    bike_shop                                   =   db.Column(db.Boolean, default=False, nullable=False)
    board_shop                                  =   db.Column(db.Boolean, default=False, nullable=False)
    bookstore                                   =   db.Column(db.Boolean, default=False, nullable=False)
    bridal_shop                                 =   db.Column(db.Boolean, default=False, nullable=False)
    business_service                            =   db.Column(db.Boolean, default=False, nullable=False)
    camera_store                                =   db.Column(db.Boolean, default=False, nullable=False)
    candy_store                                 =   db.Column(db.Boolean, default=False, nullable=False)
    car_wash                                    =   db.Column(db.Boolean, default=False, nullable=False)
    carpet_store                                =   db.Column(db.Boolean, default=False, nullable=False)
    check_cashing_service                       =   db.Column(db.Boolean, default=False, nullable=False)
    child_care_service                          =   db.Column(db.Boolean, default=False, nullable=False)
    chocolate_shop                              =   db.Column(db.Boolean, default=False, nullable=False)
    clothing_store                              =   db.Column(db.Boolean, default=False, nullable=False)
    comic_shop                                  =   db.Column(db.Boolean, default=False, nullable=False)
    construction_and_landscaping                =   db.Column(db.Boolean, default=False, nullable=False)
    convenience_store                           =   db.Column(db.Boolean, default=False, nullable=False)
    cosmetics_shop                              =   db.Column(db.Boolean, default=False, nullable=False)
    costume_shop                                =   db.Column(db.Boolean, default=False, nullable=False)
    credit_union                                =   db.Column(db.Boolean, default=False, nullable=False)
    currency_exchange                           =   db.Column(db.Boolean, default=False, nullable=False)
    department_store                            =   db.Column(db.Boolean, default=False, nullable=False)
    design_studio                               =   db.Column(db.Boolean, default=False, nullable=False)
    discount_store                              =   db.Column(db.Boolean, default=False, nullable=False)
    dive_shop                                   =   db.Column(db.Boolean, default=False, nullable=False)
    drugstore                                   =   db.Column(db.Boolean, default=False, nullable=False)
    dry_cleaner                                 =   db.Column(db.Boolean, default=False, nullable=False)
    ev_charging_station                         =   db.Column(db.Boolean, default=False, nullable=False)
    electronics_store                           =   db.Column(db.Boolean, default=False, nullable=False)
    entertainment_service                       =   db.Column(db.Boolean, default=False, nullable=False)
    event_service                               =   db.Column(db.Boolean, default=False, nullable=False)
    fabric_shop                                 =   db.Column(db.Boolean, default=False, nullable=False)
    film_studio                                 =   db.Column(db.Boolean, default=False, nullable=False)
    financial_or_legal_service      =   db.Column(db.Boolean, default=False, nullable=False)
    fireworks_store      =   db.Column(db.Boolean, default=False, nullable=False)
    fishing_store      =   db.Column(db.Boolean, default=False, nullable=False)
    flea_market      =   db.Column(db.Boolean, default=False, nullable=False)
    floating_market      =   db.Column(db.Boolean, default=False, nullable=False)
    flower_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    food_and_drink_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    frame_store      =   db.Column(db.Boolean, default=False, nullable=False)
    fruit_and_vegetable_store      =   db.Column(db.Boolean, default=False, nullable=False)
    furniture_or_home_store      =   db.Column(db.Boolean, default=False, nullable=False)
    gaming_cafe      =   db.Column(db.Boolean, default=False, nullable=False)
    garden_center      =   db.Column(db.Boolean, default=False, nullable=False)
    gas_station      =   db.Column(db.Boolean, default=False, nullable=False)
    gift_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    gun_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    hardware_store      =   db.Column(db.Boolean, default=False, nullable=False)
    health_and_beauty_service      =   db.Column(db.Boolean, default=False, nullable=False)
    herbs_and_spices_store      =   db.Column(db.Boolean, default=False, nullable=False)
    hobby_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    home_service      =   db.Column(db.Boolean, default=False, nullable=False)
    hunting_supply      =   db.Column(db.Boolean, default=False, nullable=False)
    it_services      =   db.Column(db.Boolean, default=False, nullable=False)
    insurance_office      =   db.Column(db.Boolean, default=False, nullable=False)
    internet_cafe      =   db.Column(db.Boolean, default=False, nullable=False)
    jewelry_store      =   db.Column(db.Boolean, default=False, nullable=False)
    kitchen_supply_store      =   db.Column(db.Boolean, default=False, nullable=False)
    knitting_store      =   db.Column(db.Boolean, default=False, nullable=False)
    laundromat      =   db.Column(db.Boolean, default=False, nullable=False)
    laundry_service      =   db.Column(db.Boolean, default=False, nullable=False)
    lawyer      =   db.Column(db.Boolean, default=False, nullable=False)
    leather_goods_store      =   db.Column(db.Boolean, default=False, nullable=False)
    locksmith      =   db.Column(db.Boolean, default=False, nullable=False)
    lottery_retailer      =   db.Column(db.Boolean, default=False, nullable=False)
    luggage_store      =   db.Column(db.Boolean, default=False, nullable=False)
    marijuana_dispensary      =   db.Column(db.Boolean, default=False, nullable=False)
    market      =   db.Column(db.Boolean, default=False, nullable=False)
    massage_studio      =   db.Column(db.Boolean, default=False, nullable=False)
    mattress_store      =   db.Column(db.Boolean, default=False, nullable=False)
    medical_supply_store      =   db.Column(db.Boolean, default=False, nullable=False)
    miscellaneous_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    mobile_phone_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    mobility_store      =   db.Column(db.Boolean, default=False, nullable=False)
    motorcycle_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    motorsports_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    music_store      =   db.Column(db.Boolean, default=False, nullable=False)
    nail_salon      =   db.Column(db.Boolean, default=False, nullable=False)
    newsagent      =   db.Column(db.Boolean, default=False, nullable=False)
    newsstand      =   db.Column(db.Boolean, default=False, nullable=False)
    notary      =   db.Column(db.Boolean, default=False, nullable=False)
    optical_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    other_repair_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    outdoor_supply_store      =   db.Column(db.Boolean, default=False, nullable=False)
    outlet_mall      =   db.Column(db.Boolean, default=False, nullable=False)
    outlet_store      =   db.Column(db.Boolean, default=False, nullable=False)
    paper_or_office_supplies_store      =   db.Column(db.Boolean, default=False, nullable=False)
    pawn_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    perfume_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    pet_service      =   db.Column(db.Boolean, default=False, nullable=False)
    pet_store      =   db.Column(db.Boolean, default=False, nullable=False)
    pharmacy      =   db.Column(db.Boolean, default=False, nullable=False)
    photography_lab      =   db.Column(db.Boolean, default=False, nullable=False)
    photography_studio      =   db.Column(db.Boolean, default=False, nullable=False)
    piercing_parlor      =   db.Column(db.Boolean, default=False, nullable=False)
    pop_up_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    print_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    public_bathroom      =   db.Column(db.Boolean, default=False, nullable=False)
    real_estate_office      =   db.Column(db.Boolean, default=False, nullable=False)
    record_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    recording_studio      =   db.Column(db.Boolean, default=False, nullable=False)
    recycling_facility      =   db.Column(db.Boolean, default=False, nullable=False)
    rental_service      =   db.Column(db.Boolean, default=False, nullable=False)
    salon_or_barbershop      =   db.Column(db.Boolean, default=False, nullable=False)
    sauna_or_steam_room      =   db.Column(db.Boolean, default=False, nullable=False)
    shipping_store      =   db.Column(db.Boolean, default=False, nullable=False)
    shoe_repair      =   db.Column(db.Boolean, default=False, nullable=False)
    shopping_mall      =   db.Column(db.Boolean, default=False, nullable=False)
    shopping_plaza      =   db.Column(db.Boolean, default=False, nullable=False)
    skate_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    ski_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    smoke_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    smoothie_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    souvenir_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    spa      =   db.Column(db.Boolean, default=False, nullable=False)
    sporting_goods_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    stationery_store      =   db.Column(db.Boolean, default=False, nullable=False)
    storage_facility      =   db.Column(db.Boolean, default=False, nullable=False)
    supplement_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    tailor_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    tanning_salon      =   db.Column(db.Boolean, default=False, nullable=False)
    tattoo_parlor      =   db.Column(db.Boolean, default=False, nullable=False)
    thrift_or_vintage_store      =   db.Column(db.Boolean, default=False, nullable=False)
    toy_or_game_store      =   db.Column(db.Boolean, default=False, nullable=False)
    travel_agency      =   db.Column(db.Boolean, default=False, nullable=False)
    used_bookstore      =   db.Column(db.Boolean, default=False, nullable=False)
    vape_store      =   db.Column(db.Boolean, default=False, nullable=False)
    vehicle_inspection_station      =   db.Column(db.Boolean, default=False, nullable=False)
    video_game_store      =   db.Column(db.Boolean, default=False, nullable=False)
    video_store      =   db.Column(db.Boolean, default=False, nullable=False)
    warehouse_store      =   db.Column(db.Boolean, default=False, nullable=False)
    watch_shop      =   db.Column(db.Boolean, default=False, nullable=False)

class   TravelAndTransportTrip(db.Model):

    __tablename__ = 'travel_and_transport_trip'
    

    user_id                     =   db.Column(db.String(8), unique = True,primary_key=True, nullable=False)
    airport      =   db.Column(db.Boolean, default=False, nullable=False)
    baggage_locker      =   db.Column(db.Boolean, default=False, nullable=False)
    bike_rental_or_bike_share      =   db.Column(db.Boolean, default=False, nullable=False)
    boat_rental      =   db.Column(db.Boolean, default=False, nullable=False)
    boat_or_ferry      =   db.Column(db.Boolean, default=False, nullable=False)
    border_crossing      =   db.Column(db.Boolean, default=False, nullable=False)
    bus_station      =   db.Column(db.Boolean, default=False, nullable=False)
    bus_stop      =   db.Column(db.Boolean, default=False, nullable=False)
    cable_car      =   db.Column(db.Boolean, default=False, nullable=False)
    cruise_ship      =   db.Column(db.Boolean, default=False, nullable=False)
    duty_free_shop      =   db.Column(db.Boolean, default=False, nullable=False)
    general_travel      =   db.Column(db.Boolean, default=False, nullable=False)
    heliport      =   db.Column(db.Boolean, default=False, nullable=False)
    hotel      =   db.Column(db.Boolean, default=False, nullable=False)
    intersection      =   db.Column(db.Boolean, default=False, nullable=False)
    light_rail_station      =   db.Column(db.Boolean, default=False, nullable=False)
    marine_terminal      =   db.Column(db.Boolean, default=False, nullable=False)
    metro_station      =   db.Column(db.Boolean, default=False, nullable=False)
    moving_target      =   db.Column(db.Boolean, default=False, nullable=False)
    pier      =   db.Column(db.Boolean, default=False, nullable=False)
    port      =   db.Column(db.Boolean, default=False, nullable=False)
    rv_park      =   db.Column(db.Boolean, default=False, nullable=False)
    rental_car_location      =   db.Column(db.Boolean, default=False, nullable=False)
    rest_area      =   db.Column(db.Boolean, default=False, nullable=False)
    road      =   db.Column(db.Boolean, default=False, nullable=False)
    taxi_stand      =   db.Column(db.Boolean, default=False, nullable=False)
    taxi      =   db.Column(db.Boolean, default=False, nullable=False)
    toll_booth      =   db.Column(db.Boolean, default=False, nullable=False)
    toll_plaza      =   db.Column(db.Boolean, default=False, nullable=False)
    tourist_information_center      =   db.Column(db.Boolean, default=False, nullable=False)
    train_station      =   db.Column(db.Boolean, default=False, nullable=False)
    tram_station      =   db.Column(db.Boolean, default=False, nullable=False)
    transportation_service      =   db.Column(db.Boolean, default=False, nullable=False)
    travel_lounge      =   db.Column(db.Boolean, default=False, nullable=False)
    truck_stop      =   db.Column(db.Boolean, default=False, nullable=False)
    tunnel      =   db.Column(db.Boolean, default=False, nullable=False)